#!/usr/bin/env python3
"""Generate the deterministic C++ Roman raw-correction rule table."""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2]))

from tools.typing_correction.validate_typing_correction_corpus import (
    CORPUS_ROOT,
    CORPUS_VERSION,
    EVALUATION_TARGETS,
    RELEASE_THRESHOLDS,
    RUNTIME_LIMITS,
    corpus_digest,
    load_corpus,
)


DEFAULT_OUTPUT = (
    pathlib.Path(__file__).resolve().parents[2]
    / "src"
    / "typing_correction"
    / "generated_roman_rules.h"
)
DEFAULT_KANA_OUTPUT = (
    pathlib.Path(__file__).resolve().parents[2]
    / "src"
    / "typing_correction"
    / "generated_kana_rules.h"
)
DEFAULT_HOLDOUT_OUTPUT = (
    pathlib.Path(__file__).resolve().parents[2]
    / "src"
    / "typing_correction"
    / "generated_holdout_cases.h"
)
DEFAULT_CONTRACT_OUTPUT = (
    pathlib.Path(__file__).resolve().parents[2]
    / "src"
    / "typing_correction"
    / "generated_contract.h"
)

OPERATION_NAMES = {
    "transpose": "kAdjacentTranspose",
    "omission": "kMissingKeyInsertion",
    "duplicate": "kDuplicateRemoval",
    "replacement": "kLiteralReplacement",
    "neighbor": "kNeighborSubstitution",
    "kana_modifier": "kKanaModifier",
}
COSTS = {
    "transpose": 100,
    "duplicate": 110,
    "neighbor": 120,
    "omission": 160,
    "replacement": 200,
}
KANA_COSTS = {
    "neighbor": 120,
    # A physical-key neighbor is ambiguous; an unchanged key code with a
    # modifier-sensitive key string is a more specific replay and should win
    # the bounded candidate window.
    "kana_modifier": 100,
}


def render_contract_header() -> str:
    return "\n".join(
        [
            "// Generated by tools/typing_correction/build_typing_correction_rules.py.",
            "// Do not edit this file directly; update corpus_schema.json instead.",
            "",
            "#ifndef MOZC_TYPING_CORRECTION_GENERATED_CONTRACT_H_",
            "#define MOZC_TYPING_CORRECTION_GENERATED_CONTRACT_H_",
            "",
            "#include <cstddef>",
            "#include <cstdint>",
            "",
            "namespace mozc::typing_correction {",
            "",
            f"inline constexpr size_t kTypingCorrectionMinRawBytes = {RUNTIME_LIMITS['min_raw_bytes']};",
            f"inline constexpr size_t kTypingCorrectionMaxRawBytes = {RUNTIME_LIMITS['max_raw_bytes']};",
            f"inline constexpr size_t kTypingCorrectionMaxKeyEvents = {RUNTIME_LIMITS['max_key_events']};",
            f"inline constexpr int32_t kTypingCorrectionMaxEditCost = {RUNTIME_LIMITS['max_edit_cost']};",
            f"inline constexpr size_t kTypingCorrectionMaxRawHypotheses = {RUNTIME_LIMITS['max_raw_hypotheses']};",
            f"inline constexpr size_t kTypingCorrectionMaxReadingHypotheses = {RUNTIME_LIMITS['max_reading_hypotheses']};",
            f"inline constexpr size_t kTypingCorrectionMaxEdits = {RUNTIME_LIMITS['max_edits']};",
            f"inline constexpr size_t kTypingCorrectionMaxCandidateWindowAdditions = {RUNTIME_LIMITS['max_candidate_window_additions']};",
            f"inline constexpr double kTypingCorrectionRomanCandidatePrecisionMinimum = {RELEASE_THRESHOLDS['roman']['raw_hypothesis_candidate_precision_min']:.6f};",
            f"inline constexpr double kTypingCorrectionRomanCandidateRecallMinimum = {RELEASE_THRESHOLDS['roman']['raw_hypothesis_candidate_recall_min']:.6f};",
            f"inline constexpr double kTypingCorrectionRomanTop1AccuracyMinimum = {RELEASE_THRESHOLDS['roman']['raw_hypothesis_top1_accuracy_min']:.6f};",
            f"inline constexpr double kTypingCorrectionRomanSuggestRecallMinimum = {RELEASE_THRESHOLDS['roman']['suggest_recall_min']:.6f};",
            f"inline constexpr double kTypingCorrectionRomanAutoRecallMinimum = {RELEASE_THRESHOLDS['roman']['auto_recall_min']:.6f};",
            f"inline constexpr double kTypingCorrectionRomanAutoPrecisionMinimum = {RELEASE_THRESHOLDS['roman']['auto_precision_min']:.6f};",
            f"inline constexpr double kTypingCorrectionRomanAutoFalsePositiveRateMaximum = {RELEASE_THRESHOLDS['roman']['auto_false_positive_rate_max']:.6f};",
            f"inline constexpr double kTypingCorrectionKanaCandidatePrecisionMinimum = {RELEASE_THRESHOLDS['kana']['raw_hypothesis_candidate_precision_min']:.6f};",
            f"inline constexpr double kTypingCorrectionKanaCandidateRecallMinimum = {RELEASE_THRESHOLDS['kana']['raw_hypothesis_candidate_recall_min']:.6f};",
            f"inline constexpr double kTypingCorrectionKanaTop1AccuracyMinimum = {RELEASE_THRESHOLDS['kana']['raw_hypothesis_top1_accuracy_min']:.6f};",
            f"inline constexpr double kTypingCorrectionKanaSuggestRecallMinimum = {RELEASE_THRESHOLDS['kana']['suggest_recall_min']:.6f};",
            f"inline constexpr double kTypingCorrectionKanaAutoFalsePositiveRateMaximum = {RELEASE_THRESHOLDS['kana']['auto_false_positive_rate_max']:.6f};",
            f"inline constexpr double kTypingCorrectionCandidateFalsePositiveRateMaximum = {RELEASE_THRESHOLDS['candidate_false_positive_rate_max']:.6f};",
            "",
            "}  // namespace mozc::typing_correction",
            "",
            "#endif  // MOZC_TYPING_CORRECTION_GENERATED_CONTRACT_H_",
            "",
        ]
    )


def _cpp_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render_header(root: pathlib.Path = CORPUS_ROOT) -> str:
    corpus = load_corpus(root)
    rules: list[tuple[str, str, str, str, int, bool, bool]] = []
    for case in corpus.gold:
        row = case.row
        rules.append(
            (
                row["case_id"],
                row["typed_raw"],
                row["intended_raw"],
                OPERATION_NAMES[row["operation"]],
                COSTS[row["operation"]],
                row["behavior"] == "auto",
                True,
            )
        )
    for rule in corpus.overrides:
        row = rule.row
        rules.append(
            (
                row["rule_id"],
                row["wrong"],
                row["corrected"],
                OPERATION_NAMES[row["operation"]],
                int(row["cost"]),
                row["auto_applicable"] == "true",
                row["scope"] == "full",
            )
        )

    lines = [
        "// Generated by tools/typing_correction/build_typing_correction_rules.py.",
        "// Do not edit this file directly; update the TSV corpus instead.",
        "",
        "#ifndef MOZC_TYPING_CORRECTION_GENERATED_ROMAN_RULES_H_",
        "#define MOZC_TYPING_CORRECTION_GENERATED_ROMAN_RULES_H_",
        "",
        '#include "typing_correction/roman_typing_corrector.h"',
        "",
        "namespace mozc::typing_correction {",
        "",
        f'inline constexpr char kTypingCorrectionCorpusVersion[] = "{CORPUS_VERSION}";',
        f'inline constexpr char kTypingCorrectionCorpusSha256[] = "{corpus_digest(root)}";',
        f"inline constexpr size_t kTypingCorrectionRomanGoldTargetCount = {EVALUATION_TARGETS['roman_gold']};",
        f"inline constexpr size_t kTypingCorrectionRomanNegativeTargetCount = {EVALUATION_TARGETS['roman_negative']};",
        "",
        "inline constexpr RomanRule kGeneratedRomanRules[] = {",
    ]
    for rule_id, wrong, corrected, operation, cost, auto_applicable, whole in rules:
        lines.append(
            "    {"
            f"{_cpp_string(wrong)}, {_cpp_string(corrected)}, "
            f"Operation::{operation}, {cost}, "
            f"{'true' if auto_applicable else 'false'}, "
            f"{'true' if whole else 'false'}, {_cpp_string(rule_id)}"
            "},"
        )
    lines.extend(
        [
            "};",
            "",
            "inline constexpr RomanGoldCase kGeneratedRomanGoldCases[] = {",
        ]
    )
    for case in corpus.gold:
        row = case.row
        lines.append(
            "    {"
            f"{_cpp_string(row['case_id'])}, {_cpp_string(row['typed_raw'])}, "
            f"{_cpp_string(row['intended_raw'])}, "
            f"{_cpp_string(row['intended_reading'])}, "
            f"Operation::{OPERATION_NAMES[row['operation']]}, "
            f"{'true' if row['behavior'] == 'auto' else 'false'}, "
            f"{_cpp_string(row['stratum'])}"
            "},"
        )
    lines.extend(
        [
            "};",
            "",
            "inline constexpr size_t kGeneratedRomanGoldCaseCount =",
            "    sizeof(kGeneratedRomanGoldCases) /",
            "    sizeof(kGeneratedRomanGoldCases[0]);",
            "",
            "inline constexpr RomanNegativeCase kGeneratedRomanNegativeCases[] = {",
        ]
    )
    for case in corpus.negative:
        row = case.row
        lines.append(
            "    {"
            f"{_cpp_string(row['case_id'])}, {_cpp_string(row['typed_raw'])}, "
            f"{'true' if row['raw_policy'] == 'forbidden' else 'false'}, "
            f"{'true' if row['display_policy'] == 'forbidden' else 'false'}, "
            f"{'true' if row['auto_policy'] == 'forbidden' else 'false'}, "
            f"{_cpp_string(row['stratum'])}"
            "},"
        )
    lines.extend(
        [
            "};",
            "",
            "inline constexpr size_t kGeneratedRomanNegativeCaseCount =",
            "    sizeof(kGeneratedRomanNegativeCases) /",
            "    sizeof(kGeneratedRomanNegativeCases[0]);",
            "",
            "inline constexpr size_t kGeneratedRomanRuleCount =",
            "    sizeof(kGeneratedRomanRules) / sizeof(kGeneratedRomanRules[0]);",
            "",
            "}  // namespace mozc::typing_correction",
            "",
            "#endif  // MOZC_TYPING_CORRECTION_GENERATED_ROMAN_RULES_H_",
            "",
        ]
    )
    return "\n".join(lines)


def _cpp_char(value: str) -> str:
    if len(value) != 1 or ord(value) > 0x7F:
        raise ValueError(f"kana key code must be one ASCII character: {value!r}")
    escaped = value.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{escaped}'"


def render_kana_header(root: pathlib.Path = CORPUS_ROOT) -> str:
    corpus = load_corpus(root)
    if not corpus.kana_gold or not corpus.kana_evaluation or not corpus.kana_negative:
        raise ValueError("kana corpus is required to generate the kana header")

    lines = [
        "// Generated by tools/typing_correction/build_typing_correction_rules.py.",
        "// Do not edit this file directly; update the TSV corpus instead.",
        "",
        "#ifndef MOZC_TYPING_CORRECTION_GENERATED_KANA_RULES_H_",
        "#define MOZC_TYPING_CORRECTION_GENERATED_KANA_RULES_H_",
        "",
        '#include "typing_correction/kana_typing_corrector.h"',
        "",
        "namespace mozc::typing_correction {",
        "",
        f'inline constexpr char kTypingCorrectionKanaCorpusVersion[] = "{CORPUS_VERSION}";',
        f'inline constexpr char kTypingCorrectionKanaCorpusSha256[] = "{corpus_digest(root)}";',
        f"inline constexpr size_t kTypingCorrectionKanaGoldTargetCount = {EVALUATION_TARGETS['kana_gold']};",
        f"inline constexpr size_t kTypingCorrectionKanaGoldFixtureTargetCount = {EVALUATION_TARGETS['kana_gold_fixture']};",
        f"inline constexpr size_t kTypingCorrectionKanaEvaluationTargetCount = {EVALUATION_TARGETS['kana_gold']};",
        f"inline constexpr size_t kTypingCorrectionKanaNegativeTargetCount = {EVALUATION_TARGETS['kana_negative']};",
        "",
        "inline constexpr KanaRule kGeneratedKanaRules[] = {",
    ]
    operation_names = {
        "neighbor": "kNeighborSubstitution",
        "kana_modifier": "kKanaModifier",
    }
    for case in corpus.kana_gold:
        row = case.row
        typed_code = _cpp_char(row["typed_key_codes"])
        corrected_code = _cpp_char(row["corrected_key_codes"])
        lines.append(
            "    {"
            f"{typed_code}, {_cpp_string(row['typed_key_strings'])}, "
            f"{corrected_code}, {_cpp_string(row['corrected_key_strings'])}, "
            f"Operation::{operation_names[row['operation']]}, "
            f"{KANA_COSTS[row['operation']]}, "
            f"{'true' if row['behavior'] == 'auto' else 'false'}, "
            f"{_cpp_string(row['case_id'])}"
            "},"
        )
    lines.extend(
        [
            "};",
            "",
            "inline constexpr KanaGoldCase kGeneratedKanaGoldCases[] = {",
        ]
    )
    for case in corpus.kana_gold:
        row = case.row
        lines.append(
            "    {"
            f"{_cpp_string(row['case_id'])}, "
            f"{_cpp_string(row['typed_key_codes'])}, "
            f"{_cpp_string(row['corrected_key_codes'])}, "
            f"{_cpp_string(row['typed_key_strings'])}, "
            f"{_cpp_string(row['corrected_key_strings'])}, "
            f"Operation::{operation_names[row['operation']]}, "
            f"{'true' if row['behavior'] == 'auto' else 'false'}, "
            f"{_cpp_string(row['stratum'])}"
            "},"
        )
    lines.extend(
        [
            "};",
            "",
            "inline constexpr size_t kGeneratedKanaGoldCaseCount =",
            "    sizeof(kGeneratedKanaGoldCases) / sizeof(kGeneratedKanaGoldCases[0]);",
            "",
            "inline constexpr KanaGoldCase kGeneratedKanaEvaluationCases[] = {",
        ]
    )
    for case in corpus.kana_evaluation:
        row = case.row
        lines.append(
            "    {"
            f"{_cpp_string(row['case_id'])}, "
            f"{_cpp_string(row['typed_key_codes'])}, "
            f"{_cpp_string(row['corrected_key_codes'])}, "
            f"{_cpp_string(row['typed_key_strings'])}, "
            f"{_cpp_string(row['corrected_key_strings'])}, "
            f"Operation::{operation_names[row['operation']]}, "
            f"{'true' if row['behavior'] == 'auto' else 'false'}, "
            f"{_cpp_string(row['stratum'])}"
            "},"
        )
    lines.extend(
        [
            "};",
            "",
            "inline constexpr size_t kGeneratedKanaEvaluationCaseCount =",
            "    sizeof(kGeneratedKanaEvaluationCases) / sizeof(kGeneratedKanaEvaluationCases[0]);",
            "",
            "inline constexpr KanaNegativeCase kGeneratedKanaNegativeCases[] = {",
        ]
    )
    for case in corpus.kana_negative:
        row = case.row
        lines.append(
            "    {"
            f"{_cpp_string(row['case_id'])}, "
            f"{_cpp_string(row['typed_key_codes'])}, "
            f"{_cpp_string(row['typed_key_strings'])}, "
            f"{'true' if row['raw_policy'] == 'forbidden' else 'false'}, "
            f"{'true' if row['display_policy'] == 'forbidden' else 'false'}, "
            f"{'true' if row['auto_policy'] == 'forbidden' else 'false'}, "
            f"{_cpp_string(row['stratum'])}"
            "},"
        )
    lines.extend(
        [
            "};",
            "",
            "inline constexpr size_t kGeneratedKanaNegativeCaseCount =",
            "    sizeof(kGeneratedKanaNegativeCases) / sizeof(kGeneratedKanaNegativeCases[0]);",
            "",
            "inline constexpr size_t kGeneratedKanaRuleCount =",
            "    sizeof(kGeneratedKanaRules) / sizeof(kGeneratedKanaRules[0]);",
            "",
            "}  // namespace mozc::typing_correction",
            "",
            "#endif  // MOZC_TYPING_CORRECTION_GENERATED_KANA_RULES_H_",
            "",
        ]
    )
    return "\n".join(lines)


def render_holdout_header(root: pathlib.Path = CORPUS_ROOT) -> str:
    corpus = load_corpus(root)
    if not corpus.roman_holdout or not corpus.kana_holdout:
        raise ValueError("holdout corpus is required to generate the holdout header")

    lines = [
        "// Generated by tools/typing_correction/build_typing_correction_rules.py.",
        "// Do not edit this file directly; update the TSV corpus instead.",
        "",
        "#ifndef MOZC_TYPING_CORRECTION_GENERATED_HOLDOUT_CASES_H_",
        "#define MOZC_TYPING_CORRECTION_GENERATED_HOLDOUT_CASES_H_",
        "",
        '#include "typing_correction/typing_correction.h"',
        "",
        "namespace mozc::typing_correction {",
        "",
        f"inline constexpr size_t kTypingCorrectionRomanHoldoutTargetCount = {EVALUATION_TARGETS['roman_composer_engine_holdout']};",
        f"inline constexpr size_t kTypingCorrectionKanaHoldoutTargetCount = {EVALUATION_TARGETS['kana_holdout']};",
        f"inline constexpr double kTypingCorrectionEngineE2eRecallMinimum = {RELEASE_THRESHOLDS['engine_e2e_recall_min']:.6f};",
        f"inline constexpr double kTypingCorrectionComposerReplayRecallMinimum = {RELEASE_THRESHOLDS['composer_replay_recall_min']:.6f};",
        "",
        "struct RomanHoldoutCase {",
        "  absl::string_view case_id;",
        "  absl::string_view typed_raw;",
        "  absl::string_view corrected_raw;",
        "  absl::string_view corrected_reading;",
        "  Operation operation = Operation::kLiteralReplacement;",
        "  absl::string_view stratum;",
        "};",
        "",
        "struct KanaHoldoutCase {",
        "  absl::string_view case_id;",
        "  absl::string_view typed_key_codes;",
        "  absl::string_view corrected_key_codes;",
        "  absl::string_view typed_key_strings;",
        "  absl::string_view corrected_key_strings;",
        "  Operation operation = Operation::kDuplicateRemoval;",
        "  absl::string_view stratum;",
        "};",
        "",
        "inline constexpr RomanHoldoutCase kGeneratedRomanHoldoutCases[] = {",
    ]
    for case in corpus.roman_holdout:
        row = case.row
        lines.append(
            "    {"
            f"{_cpp_string(row['case_id'])}, {_cpp_string(row['typed_raw'])}, "
            f"{_cpp_string(row['corrected_raw'])}, "
            f"{_cpp_string(row['corrected_reading'])}, "
            f"Operation::{OPERATION_NAMES[row['operation']]}, "
            f"{_cpp_string(row['stratum'])}}},"
        )
    lines.extend(
        [
            "};",
            "",
            "inline constexpr size_t kGeneratedRomanHoldoutCaseCount =",
            "    sizeof(kGeneratedRomanHoldoutCases) /",
            "    sizeof(kGeneratedRomanHoldoutCases[0]);",
            "",
            "inline constexpr KanaHoldoutCase kGeneratedKanaHoldoutCases[] = {",
        ]
    )
    for case in corpus.kana_holdout:
        row = case.row
        lines.append(
            "    {"
            f"{_cpp_string(row['case_id'])}, "
            f"{_cpp_string(row['typed_key_codes'])}, "
            f"{_cpp_string(row['corrected_key_codes'])}, "
            f"{_cpp_string(row['typed_key_strings'])}, "
            f"{_cpp_string(row['corrected_key_strings'])}, "
            f"Operation::{OPERATION_NAMES[row['operation']]}, "
            f"{_cpp_string(row['stratum'])}}},"
        )
    lines.extend(
        [
            "};",
            "",
            "inline constexpr size_t kGeneratedKanaHoldoutCaseCount =",
            "    sizeof(kGeneratedKanaHoldoutCases) /",
            "    sizeof(kGeneratedKanaHoldoutCases[0]);",
            "",
            "}  // namespace mozc::typing_correction",
            "",
            "#endif  // MOZC_TYPING_CORRECTION_GENERATED_HOLDOUT_CASES_H_",
            "",
        ]
    )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--corpus-root", type=pathlib.Path, default=CORPUS_ROOT)
    parser.add_argument("--output", type=pathlib.Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--kana-output", type=pathlib.Path, default=DEFAULT_KANA_OUTPUT
    )
    parser.add_argument(
        "--holdout-output", type=pathlib.Path, default=DEFAULT_HOLDOUT_OUTPUT
    )
    parser.add_argument(
        "--contract-output", type=pathlib.Path, default=DEFAULT_CONTRACT_OUTPUT
    )
    args = parser.parse_args(argv)
    args.contract_output.parent.mkdir(parents=True, exist_ok=True)
    args.contract_output.write_text(
        render_contract_header(), encoding="utf-8", newline="\n"
    )
    output = render_header(args.corpus_root)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8", newline="\n")
    if (args.corpus_root / "kana_gold.tsv").exists():
        kana_output = render_kana_header(args.corpus_root)
        args.kana_output.parent.mkdir(parents=True, exist_ok=True)
        args.kana_output.write_text(kana_output, encoding="utf-8", newline="\n")
        holdout_output = render_holdout_header(args.corpus_root)
        args.holdout_output.parent.mkdir(parents=True, exist_ok=True)
        args.holdout_output.write_text(
            holdout_output, encoding="utf-8", newline="\n"
        )
        print(
            f"generated {args.contract_output}, {args.output}, {args.kana_output}, "
            f"and {args.holdout_output}"
        )
    else:
        print(f"generated {args.contract_output} and {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
