#!/bin/sh

_BUILD_TARGETS="${_BUILD_TARGETS:-unix/fcitx5:fcitx5-mozkey.so unix/fcitx5:grimodex_consumer_tool server:mozc_server gui/tool:mozc_tool zenz_scorer:mozc_zenz_scorer}"

bazel build -c opt --copt=-fPIC --config oss_linux --define server=1 "$@" $_BUILD_TARGETS
