#!/bin/sh
PREFIX="${PREFIX:-/usr}"
DESTDIR="${DESTDIR:-}"

install -D -m 755 "bazel-bin/unix/fcitx5/fcitx5-mozkey.so" "${DESTDIR}${PREFIX}/lib/fcitx5/fcitx5-mozkey.so"

DESTDIR="${DESTDIR}" PREFIX="${PREFIX}" ../scripts/install_fcitx5_data
