#!/bin/sh

PREFIX="${PREFIX:-/usr}"
DESTDIR="${DESTDIR:-}"

install -D -m 755 "bazel-bin/server/mozc_server" "${DESTDIR}${PREFIX}/lib/mozkey/mozc_server"
install -D -m 755 "bazel-bin/gui/tool/mozc_tool" "${DESTDIR}${PREFIX}/lib/mozkey/mozc_tool"
if [ -x bazel-bin/zenz_scorer/mozc_zenz_scorer ]; then
  install -D -m 755 bazel-bin/zenz_scorer/mozc_zenz_scorer "${DESTDIR}${PREFIX}/lib/mozkey/mozc_zenz_scorer"
fi
install -d "${DESTDIR}${PREFIX}/share/doc/mozkey/"
install -m 644 data/installer/*.html "${DESTDIR}${PREFIX}/share/doc/mozkey/"
