// Generated by tools/typing_correction/build_typing_correction_rules.py.
// Do not edit this file directly; update the TSV corpus instead.

#ifndef MOZC_TYPING_CORRECTION_GENERATED_KANA_RULES_H_
#define MOZC_TYPING_CORRECTION_GENERATED_KANA_RULES_H_

#include "typing_correction/kana_typing_corrector.h"

namespace mozc::typing_correction {

inline constexpr char kTypingCorrectionKanaCorpusVersion[] = "v1";
inline constexpr char kTypingCorrectionKanaCorpusSha256[] = "355f185688a1b43e6afa0e6aba4f22b8676ade9a116f5409c11bbc9a934fc438";

inline constexpr KanaRule kGeneratedKanaRules[] = {
    {'5', "え", '4', "う", Operation::kNeighborSubstitution, 120, true, "K000001"},
    {'3', "あ", '3', "ぁ", Operation::kKanaModifier, 140, false, "K000002"},
    {'@', "゛", '[', "゜", Operation::kKanaModifier, 140, false, "K000003"},
    {'1', "ぬ", '2', "ふ", Operation::kNeighborSubstitution, 120, false, "K000004"},
    {'6', "お", '7', "や", Operation::kNeighborSubstitution, 120, false, "K000005"},
    {'q', "た", 'w', "て", Operation::kNeighborSubstitution, 120, false, "K000006"},
    {'w', "て", 'e', "い", Operation::kNeighborSubstitution, 120, false, "K000007"},
    {'r', "す", 't', "か", Operation::kNeighborSubstitution, 120, false, "K000008"},
    {'i', "に", 'o', "ら", Operation::kNeighborSubstitution, 120, false, "K000009"},
    {'a', "ち", 's', "と", Operation::kNeighborSubstitution, 120, false, "K000010"},
    {'d', "し", 'f', "は", Operation::kNeighborSubstitution, 120, false, "K000011"},
    {'j', "ま", 'k', "の", Operation::kNeighborSubstitution, 120, false, "K000012"},
    {'z', "つ", 'x', "さ", Operation::kNeighborSubstitution, 120, false, "K000013"},
    {'x', "さ", 'c', "そ", Operation::kNeighborSubstitution, 120, false, "K000014"},
    {'n', "み", 'm', "も", Operation::kNeighborSubstitution, 120, false, "K000015"},
    {'4', "う", '4', "ぅ", Operation::kKanaModifier, 140, false, "K000016"},
    {'5', "え", '5', "ぇ", Operation::kKanaModifier, 140, false, "K000017"},
    {'6', "お", '6', "ぉ", Operation::kKanaModifier, 140, false, "K000018"},
    {'7', "や", '7', "ゃ", Operation::kKanaModifier, 140, false, "K000019"},
    {'8', "ゆ", '8', "ゅ", Operation::kKanaModifier, 140, false, "K000020"},
};

inline constexpr KanaGoldCase kGeneratedKanaGoldCases[] = {
    {"K000001", "5", "4", "え", "う", Operation::kNeighborSubstitution, true},
    {"K000002", "3", "3", "あ", "ぁ", Operation::kKanaModifier, false},
    {"K000003", "@", "[", "゛", "゜", Operation::kKanaModifier, false},
    {"K000004", "1", "2", "ぬ", "ふ", Operation::kNeighborSubstitution, false},
    {"K000005", "6", "7", "お", "や", Operation::kNeighborSubstitution, false},
    {"K000006", "q", "w", "た", "て", Operation::kNeighborSubstitution, false},
    {"K000007", "w", "e", "て", "い", Operation::kNeighborSubstitution, false},
    {"K000008", "r", "t", "す", "か", Operation::kNeighborSubstitution, false},
    {"K000009", "i", "o", "に", "ら", Operation::kNeighborSubstitution, false},
    {"K000010", "a", "s", "ち", "と", Operation::kNeighborSubstitution, false},
    {"K000011", "d", "f", "し", "は", Operation::kNeighborSubstitution, false},
    {"K000012", "j", "k", "ま", "の", Operation::kNeighborSubstitution, false},
    {"K000013", "z", "x", "つ", "さ", Operation::kNeighborSubstitution, false},
    {"K000014", "x", "c", "さ", "そ", Operation::kNeighborSubstitution, false},
    {"K000015", "n", "m", "み", "も", Operation::kNeighborSubstitution, false},
    {"K000016", "4", "4", "う", "ぅ", Operation::kKanaModifier, false},
    {"K000017", "5", "5", "え", "ぇ", Operation::kKanaModifier, false},
    {"K000018", "6", "6", "お", "ぉ", Operation::kKanaModifier, false},
    {"K000019", "7", "7", "や", "ゃ", Operation::kKanaModifier, false},
    {"K000020", "8", "8", "ゆ", "ゅ", Operation::kKanaModifier, false},
};

inline constexpr size_t kGeneratedKanaGoldCaseCount =
    sizeof(kGeneratedKanaGoldCases) / sizeof(kGeneratedKanaGoldCases[0]);

inline constexpr KanaNegativeCase kGeneratedKanaNegativeCases[] = {
    {"KN000001", "34"},
    {"KN000002", "qwert"},
    {"KN000003", "67"},
    {"KN000004", "qaz"},
    {"KN000005", "asdfg"},
    {"KN000006", "zxcvb"},
    {"KN000007", "jkl;"},
    {"KN000008", "1-^"},
    {"KN000009", "90-"},
    {"KN000010", "@["},
    {"KN000011", ";;"},
    {"KN000012", "mm"},
    {"KN000013", "ii"},
    {"KN000014", "12"},
    {"KN000015", "uw"},
    {"KN000016", "gh"},
    {"KN000017", "bn"},
    {"KN000018", "./"},
    {"KN000019", "___"},
    {"KN000020", "6@["},
};

inline constexpr size_t kGeneratedKanaNegativeCaseCount =
    sizeof(kGeneratedKanaNegativeCases) / sizeof(kGeneratedKanaNegativeCases[0]);

inline constexpr size_t kGeneratedKanaRuleCount =
    sizeof(kGeneratedKanaRules) / sizeof(kGeneratedKanaRules[0]);

}  // namespace mozc::typing_correction

#endif  // MOZC_TYPING_CORRECTION_GENERATED_KANA_RULES_H_
