// Generated by tools/typing_correction/build_typing_correction_rules.py.
// Do not edit this file directly; update the TSV corpus instead.

#ifndef MOZC_TYPING_CORRECTION_GENERATED_HOLDOUT_CASES_H_
#define MOZC_TYPING_CORRECTION_GENERATED_HOLDOUT_CASES_H_

#include "typing_correction/typing_correction.h"

namespace mozc::typing_correction {

struct RomanHoldoutCase {
  absl::string_view case_id;
  absl::string_view typed_raw;
  absl::string_view corrected_raw;
  Operation operation = Operation::kLiteralReplacement;
};

struct KanaHoldoutCase {
  absl::string_view case_id;
  absl::string_view typed_key_codes;
  absl::string_view corrected_key_codes;
  absl::string_view typed_key_strings;
  absl::string_view corrected_key_strings;
  Operation operation = Operation::kDuplicateRemoval;
};

inline constexpr RomanHoldoutCase kGeneratedRomanHoldoutCases[] = {
    {"H000001", "teh", "the", Operation::kAdjacentTranspose},
    {"H000002", "hte", "the", Operation::kAdjacentTranspose},
    {"H000003", "gooogle", "google", Operation::kDuplicateRemoval},
    {"H000004", "bookk", "book", Operation::kDuplicateRemoval},
    {"H000005", "lone", "kone", Operation::kNeighborSubstitution},
    {"H000006", "fip", "fop", Operation::kNeighborSubstitution},
};

inline constexpr size_t kGeneratedRomanHoldoutCaseCount =
    sizeof(kGeneratedRomanHoldoutCases) /
    sizeof(kGeneratedRomanHoldoutCases[0]);

inline constexpr KanaHoldoutCase kGeneratedKanaHoldoutCases[] = {
    {"KH000001", "ll", "l", "りり", "り", Operation::kDuplicateRemoval},
    {"KH000002", "oo", "o", "らら", "ら", Operation::kDuplicateRemoval},
    {"KH000003", "rr", "r", "すす", "す", Operation::kDuplicateRemoval},
    {"KH000004", "yy", "y", "んん", "ん", Operation::kDuplicateRemoval},
};

inline constexpr size_t kGeneratedKanaHoldoutCaseCount =
    sizeof(kGeneratedKanaHoldoutCases) /
    sizeof(kGeneratedKanaHoldoutCases[0]);

}  // namespace mozc::typing_correction

#endif  // MOZC_TYPING_CORRECTION_GENERATED_HOLDOUT_CASES_H_
