// Generated by tools/typing_correction/build_typing_correction_rules.py.
// Do not edit this file directly; update the TSV corpus instead.

#ifndef MOZC_TYPING_CORRECTION_GENERATED_ROMAN_RULES_H_
#define MOZC_TYPING_CORRECTION_GENERATED_ROMAN_RULES_H_

#include "typing_correction/roman_typing_corrector.h"

namespace mozc::typing_correction {

inline constexpr char kTypingCorrectionCorpusVersion[] = "v1";
inline constexpr char kTypingCorrectionCorpusSha256[] = "355f185688a1b43e6afa0e6aba4f22b8676ade9a116f5409c11bbc9a934fc438";

inline constexpr RomanRule kGeneratedRomanRules[] = {
    {"onegia", "onegai", Operation::kAdjacentTranspose, 100, true, true, "R000001"},
    {"kudasia", "kudasai", Operation::kAdjacentTranspose, 100, true, true, "R000002"},
    {"shimaiashita", "shimaimashita", Operation::kMissingKeyInsertion, 160, false, true, "R000003"},
    {"arigatouu", "arigatou", Operation::kDuplicateRemoval, 110, true, true, "R000004"},
    {"deita", "dekita", Operation::kMissingKeyInsertion, 160, false, true, "R000005"},
    {"ohayouu", "ohayou", Operation::kDuplicateRemoval, 110, true, true, "R000006"},
    {"sakrua", "sakura", Operation::kAdjacentTranspose, 100, true, true, "R000007"},
    {"airgatou", "arigatou", Operation::kAdjacentTranspose, 100, true, true, "R000008"},
    {"oahyou", "ohayou", Operation::kAdjacentTranspose, 100, true, true, "R000009"},
    {"kani", "kanji", Operation::kMissingKeyInsertion, 160, false, true, "R000010"},
    {"kawii", "kawaii", Operation::kMissingKeyInsertion, 160, false, true, "R000011"},
    {"hajimemashte", "hajimemashite", Operation::kMissingKeyInsertion, 160, false, true, "R000012"},
    {"sakuraa", "sakura", Operation::kDuplicateRemoval, 110, true, true, "R000013"},
    {"tanukii", "tanuki", Operation::kDuplicateRemoval, 110, true, true, "R000014"},
    {"denshaa", "densha", Operation::kDuplicateRemoval, 110, true, true, "R000015"},
    {"yoroshikuu", "yoroshiku", Operation::kDuplicateRemoval, 110, true, true, "R000016"},
    {"sakora", "sakura", Operation::kLiteralReplacement, 200, false, true, "R000017"},
    {"kudasei", "kudasai", Operation::kLiteralReplacement, 200, false, true, "R000018"},
    {"ohayoo", "ohayou", Operation::kLiteralReplacement, 200, false, true, "R000019"},
    {"niko", "neko", Operation::kLiteralReplacement, 200, false, true, "R000020"},
    {"sakurq", "sakura", Operation::kNeighborSubstitution, 120, false, true, "R000021"},
    {"kudaszi", "kudasai", Operation::kNeighborSubstitution, 120, false, true, "R000022"},
    {"ohayu", "ohayou", Operation::kMissingKeyInsertion, 160, false, true, "R000023"},
    {"itekimasu", "ittekimasu", Operation::kMissingKeyInsertion, 160, false, true, "R000024"},
    {"matashita", "mataashita", Operation::kMissingKeyInsertion, 160, false, true, "R000025"},
    {"oyasuminasaii", "oyasuminasai", Operation::kDuplicateRemoval, 110, true, true, "R000026"},
    {"arigatoy", "arigatou", Operation::kNeighborSubstitution, 120, false, true, "R000027"},
    {"asobuo", "asobou", Operation::kAdjacentTranspose, 100, true, true, "R000028"},
    {"daijobu", "daijoubu", Operation::kMissingKeyInsertion, 160, false, true, "R000029"},
    {"otsukaresamaa", "otsukaresama", Operation::kDuplicateRemoval, 110, true, true, "R000030"},
    {"ia", "ai", Operation::kAdjacentTranspose, 100, false, false, "R-TRANSPOSE-IA"},
    {"iash", "imash", Operation::kMissingKeyInsertion, 160, false, false, "R-OMISSION-IASH"},
};

inline constexpr RomanGoldCase kGeneratedRomanGoldCases[] = {
    {"R000001", "onegia", "onegai", "おねがい", Operation::kAdjacentTranspose, true},
    {"R000002", "kudasia", "kudasai", "ください", Operation::kAdjacentTranspose, true},
    {"R000003", "shimaiashita", "shimaimashita", "しまいました", Operation::kMissingKeyInsertion, false},
    {"R000004", "arigatouu", "arigatou", "ありがとう", Operation::kDuplicateRemoval, true},
    {"R000005", "deita", "dekita", "できた", Operation::kMissingKeyInsertion, false},
    {"R000006", "ohayouu", "ohayou", "おはよう", Operation::kDuplicateRemoval, true},
    {"R000007", "sakrua", "sakura", "さくら", Operation::kAdjacentTranspose, true},
    {"R000008", "airgatou", "arigatou", "ありがとう", Operation::kAdjacentTranspose, true},
    {"R000009", "oahyou", "ohayou", "おはよう", Operation::kAdjacentTranspose, true},
    {"R000010", "kani", "kanji", "かんじ", Operation::kMissingKeyInsertion, false},
    {"R000011", "kawii", "kawaii", "かわいい", Operation::kMissingKeyInsertion, false},
    {"R000012", "hajimemashte", "hajimemashite", "はじめまして", Operation::kMissingKeyInsertion, false},
    {"R000013", "sakuraa", "sakura", "さくら", Operation::kDuplicateRemoval, true},
    {"R000014", "tanukii", "tanuki", "たぬき", Operation::kDuplicateRemoval, true},
    {"R000015", "denshaa", "densha", "でんしゃ", Operation::kDuplicateRemoval, true},
    {"R000016", "yoroshikuu", "yoroshiku", "よろしく", Operation::kDuplicateRemoval, true},
    {"R000017", "sakora", "sakura", "さくら", Operation::kLiteralReplacement, false},
    {"R000018", "kudasei", "kudasai", "ください", Operation::kLiteralReplacement, false},
    {"R000019", "ohayoo", "ohayou", "おはよう", Operation::kLiteralReplacement, false},
    {"R000020", "niko", "neko", "ねこ", Operation::kLiteralReplacement, false},
    {"R000021", "sakurq", "sakura", "さくら", Operation::kNeighborSubstitution, false},
    {"R000022", "kudaszi", "kudasai", "ください", Operation::kNeighborSubstitution, false},
    {"R000023", "ohayu", "ohayou", "おはよう", Operation::kMissingKeyInsertion, false},
    {"R000024", "itekimasu", "ittekimasu", "いってきます", Operation::kMissingKeyInsertion, false},
    {"R000025", "matashita", "mataashita", "またあした", Operation::kMissingKeyInsertion, false},
    {"R000026", "oyasuminasaii", "oyasuminasai", "おやすみなさい", Operation::kDuplicateRemoval, true},
    {"R000027", "arigatoy", "arigatou", "ありがとう", Operation::kNeighborSubstitution, false},
    {"R000028", "asobuo", "asobou", "あそぼう", Operation::kAdjacentTranspose, true},
    {"R000029", "daijobu", "daijoubu", "だいじょうぶ", Operation::kMissingKeyInsertion, false},
    {"R000030", "otsukaresamaa", "otsukaresama", "おつかれさま", Operation::kDuplicateRemoval, true},
};

inline constexpr size_t kGeneratedRomanGoldCaseCount =
    sizeof(kGeneratedRomanGoldCases) /
    sizeof(kGeneratedRomanGoldCases[0]);

inline constexpr RomanNegativeCase kGeneratedRomanNegativeCases[] = {
    {"N000001", "kana"},
    {"N000002", "linux"},
    {"N000003", "www"},
    {"N000004", "ssh"},
    {"N000005", "github"},
    {"N000006", "mozkey"},
    {"N000007", "onegai"},
    {"N000008", "google"},
    {"N000009", "docker"},
    {"N000010", "typescript"},
    {"N000011", "grimodex"},
    {"N000012", "fcitx"},
    {"N000013", "qwerty"},
    {"N000014", "password"},
    {"N000015", "aaaa"},
    {"N000016", "zzzz"},
    {"N000017", "test"},
    {"N000018", "nihongo"},
    {"N000019", "kudasai"},
    {"N000020", "sakura"},
};

inline constexpr size_t kGeneratedRomanNegativeCaseCount =
    sizeof(kGeneratedRomanNegativeCases) /
    sizeof(kGeneratedRomanNegativeCases[0]);

inline constexpr size_t kGeneratedRomanRuleCount =
    sizeof(kGeneratedRomanRules) / sizeof(kGeneratedRomanRules[0]);

}  // namespace mozc::typing_correction

#endif  // MOZC_TYPING_CORRECTION_GENERATED_ROMAN_RULES_H_
