// Generated by tools/typing_correction/build_typing_correction_rules.py.
// Do not edit this file directly; update corpus_schema.json instead.

#ifndef MOZC_TYPING_CORRECTION_GENERATED_CONTRACT_H_
#define MOZC_TYPING_CORRECTION_GENERATED_CONTRACT_H_

#include <cstddef>
#include <cstdint>

namespace mozc::typing_correction {

inline constexpr size_t kTypingCorrectionMinRawBytes = 4;
inline constexpr size_t kTypingCorrectionMaxRawBytes = 64;
inline constexpr size_t kTypingCorrectionMaxKeyEvents = 64;
inline constexpr int32_t kTypingCorrectionMaxEditCost = 300;
inline constexpr size_t kTypingCorrectionMaxRawHypotheses = 16;
inline constexpr size_t kTypingCorrectionMaxReadingHypotheses = 3;
inline constexpr size_t kTypingCorrectionMaxKanaConversionReadingHypotheses = 16;
inline constexpr size_t kTypingCorrectionMaxEdits = 1;
inline constexpr size_t kTypingCorrectionMaxCandidateWindowAdditions = 2;
inline constexpr bool kTypingCorrectionKanaDisplayRequiresCostAdvantage = true;
inline constexpr double kTypingCorrectionRomanCandidatePrecisionMinimum = 0.050000;
inline constexpr double kTypingCorrectionRomanCandidateRecallMinimum = 0.900000;
inline constexpr double kTypingCorrectionRomanTop1AccuracyMinimum = 0.950000;
inline constexpr double kTypingCorrectionRomanSuggestRecallMinimum = 0.900000;
inline constexpr double kTypingCorrectionRomanAutoRecallMinimum = 0.900000;
inline constexpr double kTypingCorrectionRomanAutoPrecisionMinimum = 0.900000;
inline constexpr double kTypingCorrectionRomanAutoFalsePositiveRateMaximum = 0.000000;
inline constexpr double kTypingCorrectionKanaCandidatePrecisionMinimum = 0.050000;
inline constexpr double kTypingCorrectionKanaCandidateRecallMinimum = 0.900000;
inline constexpr double kTypingCorrectionKanaTop1AccuracyMinimum = 0.150000;
inline constexpr double kTypingCorrectionKanaSuggestRecallMinimum = 0.900000;
inline constexpr double kTypingCorrectionKanaAutoFalsePositiveRateMaximum = 0.000000;
inline constexpr double kTypingCorrectionCandidateFalsePositiveRateMaximum = 0.000000;

}  // namespace mozc::typing_correction

#endif  // MOZC_TYPING_CORRECTION_GENERATED_CONTRACT_H_
